base_url = "http://dataservice.accuweather.com"
autocomplete_endpoint = "locations/v1/cities/autocomplete?apikey={0}&q={1}"
current_conditions_endpoint = "currentconditions/v1/{0}?apikey={1}&details=true"
hourly_forecast_endpoint = "forecasts/v1/hourly/12hour/{0}?apikey={1}&metric=true&details=true"
one_day_forecast_endpoint = "forecasts/v1/daily/1day/{0}?apikey={1}&metric=true&details=true"
five_day_forecast_endpoint = "forecasts/v1/daily/5day/{0}?apikey={1}&metric=true&details=true"
